darkmode: true
footer:
  icon:
    name: fa fa-user
    color: "#808080"

creative_commons:
  license: by-nc-sa
  sidebar: true
  post: true
  language: zh-TW

scheme: Mist

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  # archives: /archives/ || fa fa-archive
  privacy: /about/privacy-policy || fas fa-user-shield

sidebar:
  display: hide

social:
  GitHub: https://github.com/j4nusl1n || fab fa-github
  Resume: /about/resume || fa fa-file-text

local_search:
  enable: true
  trigger: manual

google_analytics:
  tracking_id: G-648VTZD170

custom_file_path:
  head: source/_data/head.njk
  sidebar: source/_data/sidebar.njk

# Allow to cache content generation.
cache:
  enable: true

# Remove unnecessary files after hexo generate.
minify: false

# Open graph settings
# See: https://hexo.io/docs/helpers#open-graph
open_graph:
  enable: true
  options:
    type: blog

# Show multilingual switcher in footer.
language_switcher: false

# ---------------------------------------------------------------
# Comments Settings
# See: https://theme-next.js.org/docs/third-party-services/comments
# ---------------------------------------------------------------

# Multiple Comment System Support
comments:
  # Available values: tabs | buttons
  style: tabs
  # Choose a comment system to be displayed by default.
  # Available values: disqus | disqusjs | changyan | livere | gitalk | utterances
  active: disqus
  # Setting `true` means remembering the comment system selected by the visitor.
  storage: true
  # Lazyload all comment systems.
  lazyload: false
  # Modify texts or order for any naves, here are some examples.
  nav:
    #disqus:
    #  text: Load Disqus
    #  order: -1
    #gitalk:
    #  order: -2

# Disqus
# For more information: https://disqus.com
disqus:
  enable: true
  shortname: januslin
  count: true

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab:
  android_manifest: /site.webmanifest

recent_post:
  enable: true
  title: 近期文章
  layout: block
